<% root_path='/tmp/kitchen' %>

driver:
  name: docker
  use_sudo: false
  privileged: true

platforms:
  - name: debian

provisioner:
  name: salt_solo
  is_file_root: true
  root_path: <%= root_path %>
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - .bundle
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE
    - vendor
    - docs
  state_top:
    base:
      '*':
        - tests.sandbox
  pillars:
    kitchen.sls:
      kitchen:
        provisioner:
          root_path: <%= root_path %>
        test_key: 'test_value'
    carbon_config.sls:
      gitstack_config:
        ext_pillar:
          - gitstack:
              stack: _stack/stack.cfg
              repo: file://<%= root_path %>/srv/salt/tests/repo_a
              branch: master
          - git:
            - master file://<%= root_path %>/srv/salt/tests/repo_a
    nitrogen_config.sls:
      gitstack_config:
        ext_pillar:
          - gitstack:
            - master file://<%= root_path %>/srv/salt/tests/repo_a:
              - stack: _stack/stack.cfg
            - master file://<%= root_path %>/srv/salt/tests/repo_b:
              - stack: _stack/stack.cfg
              - root: pillar1
              - name: repo_b1
            - master file://<%= root_path %>/srv/salt/tests/repo_b:
              - stack: _stack/stack.cfg
              - root: pillar2
              - name: repo_b2
          - git:
            - master file://<%= root_path %>/srv/salt/tests/repo_a
            - master file://<%= root_path %>/srv/salt/tests/repo_b:
              - root: pillar1
              - name: repo_b1
            - master file://<%= root_path %>/srv/salt/tests/repo_b:
              - root: pillar2
              - name: repo_b2

suites:
  - name: 2016-11-9-legacy
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2016.11.9
      pillars: { top.sls: { base: { '*': [ kitchen, carbon_config ] } } }
  - name: 2017-7-4-legacy
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2017.7.4
      pillars: { top.sls: { base: { '*': [ kitchen, carbon_config ] } } }
  - name: 2017-7-4-multirepo
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2017.7.4
      pillars: { top.sls: { base: { '*': [ kitchen, nitrogen_config ] } } }
  - name: 2017-7-5-legacy
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2017.7.5
      pillars: { top.sls: { base: { '*': [ kitchen, carbon_config ] } } }
  - name: 2017-7-5-multirepo
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2017.7.5
      pillars: { top.sls: { base: { '*': [ kitchen, nitrogen_config ] } } }
  - name: 2017-7-6-legacy
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2017.7.6
      pillars: { top.sls: { base: { '*': [ kitchen, carbon_config ] } } }
  - name: 2017-7-6-multirepo
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2017.7.6
      pillars: { top.sls: { base: { '*': [ kitchen, nitrogen_config ] } } }
  - name: 2017-7-7-legacy
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2017.7.7
      pillars: { top.sls: { base: { '*': [ kitchen, carbon_config ] } } }
  - name: 2017-7-7-multirepo
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2017.7.7
      pillars: { top.sls: { base: { '*': [ kitchen, nitrogen_config ] } } }
  - name: 2018-3-0-legacy
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2018.3.0
      pillars: { top.sls: { base: { '*': [ kitchen, carbon_config ] } } }
  - name: 2018-3-0-multirepo
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2018.3.0
      pillars: { top.sls: { base: { '*': [ kitchen, nitrogen_config ] } } }
  - name: 2018-3-1-legacy
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2018.3.1
      pillars: { top.sls: { base: { '*': [ kitchen, carbon_config ] } } }
  - name: 2018-3-1-multirepo
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2018.3.1
      pillars: { top.sls: { base: { '*': [ kitchen, nitrogen_config ] } } }
  - name: 2018-3-2-legacy
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2018.3.2
      pillars: { top.sls: { base: { '*': [ kitchen, carbon_config ] } } }
  - name: 2018-3-2-multirepo
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2018.3.2
      pillars: { top.sls: { base: { '*': [ kitchen, nitrogen_config ] } } }
verifier:
  name: shell
  remote_exec: false
  command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o LogLevel=ERROR -i ${KITCHEN_SSH_KEY} -p ${KITCHEN_PORT} ${KITCHEN_USERNAME}@${KITCHEN_HOSTNAME} sh <%= root_path %>/srv/salt/tests/suites/${KITCHEN_SUITE##*-}/verify.sh
