<% provisioner_root_path='/tmp/kitchen' %>

driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  is_file_root: true
  root_path: <%= provisioner_root_path %>
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE

platforms:
  - name: debian
  # - name: centos-7.4
  #   driver_config:
  #     run_command: /usr/lib/systemd/systemd
  # - name: debian-8.4
  #   driver_config:
  #     run_command: /lib/systemd/systemd

suites:
  - name: nitrogen
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2017.7
      state_top:
        base:
          '*':
            - test.sandbox
      pillars:
        top.sls:
          base:
            '*':
              - gitstack_config
              - kitchen
        kitchen.sls:
          kitchen:
            provisioner:
              root_path: <%= provisioner_root_path %>
        gitstack_config.sls:
          gitstack_config:
            ext_pillar:
              - gitstack: 
                  stack: _stack/stack.cfg
                  repo: file://<%= provisioner_root_path %>/srv/salt/test
                  branch: master
              - git: 
                - master file://<%= provisioner_root_path %>/srv/salt/test

verifier:
  name: shell
  remote_exec: false
  command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o LogLevel=ERROR -i ${KITCHEN_SSH_KEY} -p ${KITCHEN_PORT} ${KITCHEN_USERNAME}@${KITCHEN_HOSTNAME} sh <%= provisioner_root_path %>/srv/salt/test/suites/${KITCHEN_SUITE}/verify.sh
