<% root_path='/tmp/kitchen' %>

driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  is_file_root: true
  root_path: <%= root_path %>
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE
  pillars:
    kitchen.sls:
      kitchen:
        provisioner:
          root_path: <%= root_path %>

platforms:
  - name: debian

suites:
  - name: nitrogen
    provisioner:
      salt_bootstrap_options: -X -n -p git -p python-pygit2 stable 2017.7
      state_top:
        base:
          '*':
            - tests.sandbox
      pillars:
        top.sls:
          base:
            '*':
              - kitchen
              - gitstack_config
        gitstack_config.sls:
          gitstack_config:
            ext_pillar:
              - gitstack: 
                  stack: _stack/stack.cfg
                  repo: file://<%= root_path %>/srv/salt/tests
                  branch: master
              - git: 
                - master file://<%= root_path %>/srv/salt/tests

verifier:
  name: shell
  remote_exec: false
  command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o LogLevel=ERROR -i ${KITCHEN_SSH_KEY} -p ${KITCHEN_PORT} ${KITCHEN_USERNAME}@${KITCHEN_HOSTNAME} sh <%= root_path %>/srv/salt/tests/suites/${KITCHEN_SUITE}/verify.sh
